### ISSUE TITLE
Cluttered output

### ISSUE THREAD

**Issue by monacofj** [so-ii-2019/sh19-cash#10]
The example-template outputs

'$:  date
  Pipeline has 1 command(s)
  Run pipeline in foreground
  Command 0 has 1 argument(s): date 

$:  Sat 20 Jul 00:34:03 -03 2019`

This was only to illustrate how `libposixeg` parser works. Your shell should not show this meta information. Only the command output should be produced.

This should be very easy to solve.

**Comment by monacofj** [comment]
This may be related to #11 .

**Comment by cassianomaia** [comment]
Resolvido no commit fc058837032631c47e209f87010f09b1e4aba2d3
