### ISSUE TITLE
Unsuitable built-ins

### ISSUE THREAD

**Issue by monacofj** [so-ii-2019/sh19-cash#12]
It's praisable the effort to implement commands such as `ls` and others.
However, there is actually no point in reimplementing external commands such as `/bin/ls`, which already fulfill POSIX functionality (e.g. build-in `ls` does not support option `-l`.

While `cd` should necessarily be built-in, the whole point of the shell project is to be able to execute external commands.

**Comment by monacofj** [comment]
Fixing this is easy: just remove unnecessary built-in commands.

**Comment by cassianomaia** [comment]
Ao invés de remover os comandos, optamos por deixar os mesmos comentados.
Realizado no commit 3e376ee3d3c1ca084ceed23a24804d2d468875c7
