### ISSUE TITLE
IO redirection eats up all CPU

### ISSUE THREAD

**Issue by monacofj** [so-ii-2019/sh19-cash#14]
Every time I tried IO redirection with something like

`echo "hello" > out.txt`

my laptop's CPU consumption skyrocket and rendered the system unusable, requiring reboot.

**Comment by monacofj** [comment]
Latter on I realized that `echo` in this case was being executed as built-in command and the aforementioned CPU exhaustion was, actually, a consequence of issue #13 

Please confirm and close this issue.

**Comment by cassianomaia** [comment]
Resolvido em conjunto com as issues #12 e #13
