### ISSUE TITLE
Use sysfatal

### ISSUE THREAD

**Issue by monacofj** [so-ii-2019/sh19-cash#5]
To check for system-level errors, it's better to use posixeg's sysfatal()
rather than fatal(). Your current build generate lots of warnings because
second argument of fatal() can't be NULL.

**Comment by monacofj** [comment]
Tip: see `posixeg/debug.h`

**Comment by cassianomaia** [comment]
Foram trocados os fatal() pelo uso de sysfatal(), no commit da89cf263e213ba91ba9a11ec6886bab932506f0
