### ISSUE TITLE
Get rid of warnings after fixing issue 2

### ISSUE THREAD

**Issue by monacofj** [so-ii-2019/sh19-cash#6]
If you fix issue #2, you should now get lots of warnings regarding undefined symbols when compiling `main.c` (because now it doesn't know about functions defined in `commands.c` anymore).  One thing you can do about it is to create a corresponding `commands.h` and include it in `main.c`.

**Comment by marianacavichioli** [comment]
Corrigido através do commit [78004d6](https://github.com/so-ii-2019/sh19-cash/commit/78004d65bfab1819b4c3adf3a0edafa98c545b02)
